# Generated by Django 5.1 on 2024-10-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_userprofile_follower_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follower',
            new_name='followers',
        ),
    ]
