# Generated by Django 5.1 on 2024-11-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_post_hearts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hearts',
        ),
        migrations.AddField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
