# Generated by Django 5.1 on 2024-11-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
