# Generated by Django 5.1 on 2024-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='default_room', max_length=255, unique=True),
        ),
    ]
