# Generated by Django 5.1 on 2024-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_groupmembershiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='Chat Room', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='GroupMembershipRequest',
        ),
    ]
