# Generated by Django 5.1 on 2024-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_alter_conversation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='ChatROOM', max_length=255, unique=True),
        ),
    ]
