# Generated by Django 5.1 on 2024-12-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
