# Generated by Django 5.1 on 2024-12-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
