# Generated by Django 5.1 on 2024-12-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_conversation_type_alter_conversation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='default_room', max_length=255, unique=True),
        ),
    ]
