# Generated by Django 5.1 on 2024-12-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0035_alter_conversation_name_alter_message_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
