# Generated by Django 5.1 on 2024-12-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0042_message_is_read_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
