# Generated by Django 5.1 on 2024-12-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0044_message_is_read_message_recipient'),
        ('social', '0045_fix_invalid_recipients'),
    ]

    operations = [
    ]
