# Generated by Django 5.1 on 2024-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0046_merge_20241215_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
