# Generated by Django 5.1.4 on 2024-12-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0051_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
