# Generated by Django 5.1.4 on 2024-12-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0052_remove_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('like', 'Like')], default='comment', max_length=50),
        ),
    ]
