# Generated by Django 5.1.4 on 2024-12-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0056_notification_post_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('like', 'Like'), ('share', 'Share'), ('reply', 'Reply')], default='comment', max_length=50),
        ),
    ]
