# Generated by Django 5.1.4 on 2024-12-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0058_userprofile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
    ]
