# Generated by Django 5.1.4 on 2025-01-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0064_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_files/')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='University of Antique Main Campus', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='files',
            field=models.ManyToManyField(blank=True, to='social.eventfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, to='social.eventimage'),
        ),
    ]
