# Generated by Django 5.1.4 on 2025-01-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0065_eventfile_eventimage_rename_start_time_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('like', 'Like'), ('share', 'Share'), ('reply', 'Reply'), ('event', 'Event')], default='comment', max_length=50),
        ),
    ]
