# Generated by Django 5.1.4 on 2025-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0066_message_file_message_image_alter_message_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
