# Generated by Django 5.1.7 on 2025-04-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0069_hashtag_group_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='social.hashtag'),
        ),
    ]
