# Generated by Django 5.1.7 on 2025-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0072_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='feedback_text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feature',
            field=models.CharField(blank=True, choices=[('Account Setup', 'Account Setup'), ('Post Creation', 'Post Creation'), ('Notifications', 'Notifications'), ('Profile Settings', 'Profile Settings'), ('Messages', 'Messages'), ('Search', 'Search'), ('Design', 'Design'), ('Event Creation', 'Event Creation'), ('Follower/Following', 'Follower/Following'), ('Groups', 'Groups'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_screenshots/'),
        ),
    ]
