# Generated by Django 5.1.7 on 2025-04-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0075_groupjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='profile_image',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default_profile.png', null=True, upload_to='uploads/group_images'),
        ),
    ]
