# Generated by Django 5.1.7 on 2025-04-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0077_grouprule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
