# Generated by Django 5.1.7 on 2025-04-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0080_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
