# Generated by Django 5.1.7 on 2025-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0081_group_banner_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupjoinrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from the user', null=True),
        ),
    ]
