# Generated by Django 5.1.7 on 2025-04-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0082_groupjoinrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests_set', to='social.group'),
        ),
    ]
