# Generated by Django 5.1.7 on 2025-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0083_alter_groupjoinrequest_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='baranggay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('inside', 'Inside University of Antique Main Campus'), ('outside', 'Outside')], default='inside', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='room_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(editable=False, max_length=500),
        ),
    ]
