# Generated by Django 5.1.7 on 2025-04-26 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0084_event_baranggay_event_building_event_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='baranggay',
            new_name='barangay',
        ),
    ]
