# Generated by Django 5.1.7 on 2025-04-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0085_rename_baranggay_event_barangay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='event',
            name='building',
        ),
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='event',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='province',
        ),
        migrations.RemoveField(
            model_name='event',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='University of Antique Main Campus', max_length=255),
        ),
    ]
