# Generated by Django 5.1.7 on 2025-04-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0086_remove_event_barangay_remove_event_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('inside', 'Inside the University'), ('outside', 'Outside the University')], default='inside', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='room_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='specific_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
