# Generated by Django 5.1.7 on 2025-04-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0087_remove_event_location_event_barangay_event_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
