# Generated by Django 5.1.7 on 2025-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0088_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
