# Generated by Django 5.1.7 on 2025-04-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0090_eventreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreminder',
            name='reminder_date',
            field=models.DateTimeField(),
        ),
    ]
