# Generated by Django 5.1.7 on 2025-04-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0091_alter_eventreminder_reminder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreminder',
            name='reminder_date',
        ),
    ]
