# Generated by Django 5.1.7 on 2025-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0092_remove_eventreminder_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
