# Generated by Django 5.1.7 on 2025-04-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0093_eventreminder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
