# Generated by Django 5.2 on 2025-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0099_message_is_deleted_message_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
