# Generated by Django 5.2 on 2025-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0100_remove_userprofile_is_banned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='banned_until',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
