# Generated by Django 5.2 on 2025-05-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0101_remove_userprofile_banned_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
