# Generated by Django 5.2 on 2025-05-03 11:16

from django.utils import timezone
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0104_banneduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneduser',
            options={'verbose_name': 'Banned User', 'verbose_name_plural': 'Banned Users'},
        ),
        migrations.RenameField(
            model_name='banneduser',
            old_name='reason',
            new_name='ban_reason',
        ),
        migrations.RemoveField(
            model_name='banneduser',
            name='banned_at',
        ),
        migrations.RemoveField(
            model_name='banneduser',
            name='unbanned_at',
        ),
        migrations.AddField(
            model_name='banneduser',
            name='ban_date',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banneduser',
            name='ban_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banneduser',
            name='banned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
