# Generated by Django 5.2 on 2025-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0106_alter_banneduser_ban_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneduser',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
