# Generated by Django 5.2 on 2025-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0107_alter_banneduser_ban_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneduser',
            name='ban_reason',
            field=models.CharField(choices=[('SPAM', 'Spam'), ('ABUSIVE_BEHAVIOR', 'Abusive Behavior'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
