# Generated by Django 5.2 on 2025-05-03 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0108_alter_banneduser_ban_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneduser',
            options={},
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
