# Generated by Django 5.2 on 2025-05-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0110_alter_banneduser_options_alter_banneduser_banned_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannedUser',
        ),
    ]
