# Generated by Django 5.2 on 2025-05-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0112_banneduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
