# Generated by Django 5.2 on 2025-05-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0114_userunderinvestigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneduser',
            name='ban_duration_days',
            field=models.IntegerField(default=0),
        ),
    ]
