# Generated by Django 5.2 on 2025-05-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0116_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_evidence',
            field=models.BooleanField(default=False),
        ),
    ]
