# Generated by Django 5.2 on 2025-05-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0118_userprofile_course_userprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
