# Generated by Django 5.2 on 2025-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0119_remove_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('BSIT', 'BSIT'), ('BSCS', 'BSCS'), ('BSIS', 'BSIS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, choices=[('Section A', 'Section A'), ('Section B', 'Section B'), ('Section C', 'Section C')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_level',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20, null=True),
        ),
    ]
