municipality_barangay_data = {
    'Anini-y': ['Bayo Grande', 'Bayo Pequeño', 'Butuan', 'Casay', 'Cato-ogan', 'Guinbangaan', 'Igbarabatuan', 'Igpalge', 'Igtumarom', 'Lisub A', 'Lisub B', 'Mabuyong', 'Maria', 'Maybato Norte', 'Maybato Sur', 'Poblacion', 'Sagua', 'Salazar', 'San Francisco', 'San Ramon', 'San Roque', 'Tagaytay', 'Tigbobolo', 'Tigvahan'],
    'Barbaza': ['Baghari', 'Bahuyan', 'Beri', 'Bigaa', 'Binangbang', 'Cadiao', 'Calapadan', 'Capoyuan', 'Cuba', 'Ingwan', 'Ipil', 'Jinalinan', 'Lanas', 'Langawan', 'Lombuyan', 'Lucio', 'Malabor', 'Magsaysay', 'Marigne', 'Mayabay', 'Mayos', 'Nalusdan', 'Napo', 'Nazaret', 'Panabungan', 'Poblacion', 'San Antonio', 'San Ramon', 'Soligao', 'Tabongtabong', 'Tig-Alaran', 'Yapo'],
    'Belison': ['Borocboroc', 'Cantuna', 'Ilaures', 'Magsaysay', 'Manabuan', 'Maradiona', 'Poblacion', 'Puangi', 'Santo Tomas', 'Bugarot (Bugaroc)', 'Sinundolan'],
    'Bugasong': ['Alangalang', 'Aranas', 'Balangbang', 'Buhang', 'Cabangahan', 'Ilihan', 'Jinalinan', 'La Granja', 'Maalat', 'Mablad', 'Mahabangbaybay', 'Mambiranan', 'Manlalay', 'Maradukan', 'Nato', 'Paliwan', 'Pangalcagan', 'Sabang East', 'Sabang West', 'Tagudtud', 'Talaban', 'Tontonan', 'Tubungan', 'Yapu'],
    'Culasi': ['Alojipan', 'Bagacay', 'Balua', 'Batbatan Island', 'Bayan', 'Binanogan', 'Cadoldolan', 'Caridad', 'Carit-an', 'Culasi', 'Esperanza', 'Ferrol', 'General Fullon', 'Hacienda', 'Ipilan', 'Jalandoni', 'Jamul-awon', 'Lacaron', 'Magsaysay', 'Malacañang', 'Malalison Island', 'Maniguin Island', 'Naba', 'Osorio', 'Panlagangan', 'Poblacion', 'Punta', 'Putian', 'Salde', 'San Antonio', 'San Gregorio', 'San Juan', 'San Luis', 'San Pascual', 'San Vicente', 'Simbola', 'Tigbalua', 'Tinabusan', 'Tomao', 'Valderama'],
    'Hamtic': ['Apdo', 'Asluman', 'Banawon', 'Bia-an', 'Bongbongan I', 'Bongbongan II', 'Botbot', 'Bugnay', 'Cuba', 'Dahikan', 'General Fullon', 'Guintas', 'Igbical', 'Igbucagay', 'Inabasan', 'Ingwan-Batangan', 'La Paz', 'Poblacion 1', 'Poblacion 2', 'Poblacion 3', 'Poblacion 4', 'Poblacion 5', 'Pu-ao', 'Suba', 'Tibiao', 'Tobias Fornier', 'Ulbujan'],
    'Laua-an': ['Bailan', 'Bari', 'Bariri', 'Boton', 'Budbudan', 'Bugas', 'Cagbagacay', 'Daguisan', 'Guiamon', 'Guisijan', 'Igtadiao', 'Inabasan', 'Mabay', 'Magsaysay', 'Maria', 'Mauno', 'Maybunga', 'Panlagangan', 'Poblacion', 'Pu-ao', 'San Ramon', 'Santiago', 'Sibacungan', 'Tigunauan'],
    'Libertad': ['Abaca', 'Agbobolo', 'Alibujon', 'Aningalan', 'Bagumbayan', 'Banban', 'Barusbus', 'Binalay', 'Binolho', 'Bongbong', 'Buliaran', 'Cabulihan', 'Cangaranan', 'Cansilayan', 'Centro Este', 'Centro Weste', 'Cuba', 'Dalipe', 'Dapdapan', 'Eva', 'Garcia', 'Getulio', 'Gines', 'Ilicod', 'Inyawan', 'Jubasan', 'Lacsican', 'Libas', 'Libo-on', 'Lingganay', 'Lomboy', 'Mabugnao', 'Maramig', 'Masantol', 'Napo', 'Pangili', 'Pajo', 'Panangkilon', 'Paz', 'Puerto', 'Punta', 'Purok 1', 'Purok 2', 'Purok 3', 'Purok 4', 'Putican', 'Santa Cruz', 'Santo Rosario', 'Tagbiri', 'Tigbao', 'Tinigbas', 'Tinindugan', 'Tucalan'],
    'Pandan': ['Aracay', 'Badiangan', 'Bagumbayan', 'Baybay', 'Bocana', 'Buang', 'Cabugao', 'Candari', 'Carmelo', 'Centro Sur (Poblacion)', 'Dumrog', 'Duyong', 'Fragante', 'Guia', 'Idiacacan', 'Jinalinan', 'Luhod-Bayang', 'Maadios', 'Malabor', 'Mangabang', 'Napo', 'Nauring', 'Patria', 'Perfecta', 'San Andres', 'San Joaquin', 'Santa Ana', 'Santa Cruz', 'Santo Rosario', 'Talolong', 'Tingib'],
    'Patnongon': ['Alvaña', 'Amparo', 'Balucuan', 'Banbanan', 'Belison', 'Biga-a', 'Carit-an', 'Cuyapiao', 'Gibon', 'Gines', 'La Rioja', 'Laguinbanwa', 'Magsaysay', 'Manapla', 'Poblacion', 'Quezon', 'Salazar', 'San Isidro', 'San Ramon', 'Santiago', 'Villa Cruz', 'Villa Flores', 'Villa Laua-an', 'Villa Sal', 'Villavert-Jimenez'],
    'San Jose de Buenavista': ['Atabay', 'Badiang', 'Barangay 1 (Poblacion)', 'Barangay 2 (Poblacion)', 'Barangay 3 (Poblacion)', 'Barangay 4 (Poblacion)', 'Barangay 5 (Poblacion)', 'Barangay 6 (Poblacion)', 'Barangay 7 (Poblacion)', 'Barangay 8 (Poblacion)', 'Bariri', 'Bugarot (Bugaroc)', 'Cansadan (Cansadan-Tubudan)', 'Durog', 'Fundamental', 'Igbonglo', 'Inabasan', 'Madrangca', 'Magcalon', 'Malaiba', 'Maybato Norte', 'Maybato Sur', 'Mojon', 'Pantao', 'San Angel', 'San Fernando', 'San Pedro', 'Supa'],
    'San Remigio': ['Aningalan', 'Atabay', 'Bagumbayan', 'Baladjay', 'Banbanan', 'Barangbang', 'Bawang', 'Bugo', 'Bulalacao', 'Cabiawan', 'Cabunga-an', 'Cadolonan', 'Calag-itan', 'Carawisan I', 'Carawisan II', 'General Fullon', 'General Luna', 'Igbucagay', 'Insubuan', 'La Union', 'Lapak', 'Lapuz', 'Lumpa', 'Malabor', 'Nagbangi I', 'Nagbangi II', 'Nasuli', 'Osorio I', 'Osorio II', 'Panpanan I', 'Panpanan II', 'Poblacion', 'Ramon Magsaysay', 'Rizal', 'San Rafael', 'Sinundolan', 'Sumaray', 'Trinidad', 'Tubudan', 'Villar', 'Walker'],
    'Sebaste': ['Abiera', 'Agnaga','Aguila', 'Badiang', 'Balogo', 'Bugasong', 'Calamnuan', 'Caluya', 'Duyong', 'Igbobon', 'Igbonglo', 'Igcasuad (Igcasuad-San Isidro)', 'Igdalaguit', 'Igdarapdap', 'Iglanot', 'Iglinab', 'Igtalongon', 'Lawigan', 'Lumalay', 'P. Javier', 'Poblacion', 'Salazar', 'San Isidro', 'Sebaste South', 'Sibolo', 'Tigbauan', 'Villa Florenda'],
    'Sibalom': ['Abiera', 'Aningalan', 'Aurora', 'Badiang', 'Balogo', 'Bugasong', 'Calamnuan', 'Caluya', 'Duyong', 'Igbobon', 'Igbonglo', 'Igcasuad (Igcasuad-San Isidro)', 'Igdalaguit', 'Igdarapdap', 'Iglanot', 'Iglinab', 'Igtalongon', 'Lawigan', 'Lumalay', 'P. Javier', 'Poblacion', 'Salazar', 'San Isidro', 'Sebaste South', 'Sibolo', 'Tigbauan', 'Villa Florenda'],
    'Tibiao': ['Alangalang', 'Alegre', 'Ambilay', 'Bandoja', 'Barangbang', 'Bato', 'Biga', 'Bugas', 'Buhay', 'Calamnuan', 'Culasi', 'Datu Sumakwel', 'Dumara', 'Encarnacion', 'La Paz', 'Malabor', 'Malaiba', 'Matarimon', 'Monserrat', 'Navas', 'Poblacion', 'Salazar', 'San Francisco Norte', 'San Francisco Sur', 'San Isidro', 'Santo Rosario', 'Tiguis', 'Tiguis Nuevo', 'Tubod', 'Villa Florenda'],
    'Tobias Fornier': ['Abaca', 'Aras-Asan', 'Arobo', 'Atabay', 'Bagumbayan', 'Balud', 'Banica', 'Barasanan A', 'Barasanan B', 'Barasanan C', 'Bariri', 'Bato', 'Bugnay', 'Bulawangan', 'Cabong', 'Cadiao', 'Cagbatang', 'Cagbayang', 'Cagsalay', 'Calapadan', 'Calamnuan', 'Cubay', 'Cuyapiao', 'Dapdap', 'Dumiles', 'Igbalangao', 'Igbangcal', 'Igbon', 'Igcabutong', 'Igcado', 'Igcalawagan', 'Igcasicad (San Pedro)', 'Igdalaguit', 'Iglanot', 'Iglinab', 'Igtalongon', 'Lawigan', 'Lumalay', 'Mabini', 'Malabor', 'Malinao', 'Manaling', 'Masayo', 'Nagsubuan', 'Paciencia', 'Poblacion Norte', 'Poblacion Sur', 'Portillo', 'Salvacion', 'San Ramon', 'Santo Tomas', 'Sapao', 'Socorro', 'Tacbuyan', 'Tene', 'Villaflores'],
    'Valderrama': ['Alon', 'Bakiad', 'Balua', 'Binanog', 'Borocboroc', 'Bugnay', 'Bulan-bulan', 'Bungsod', 'Cabdangan', 'Cabisil', 'Cananghan', 'Candari', 'Cansalminao', 'Cristobal', 'Dariwan', 'Guintas', 'Iglinab', 'Igmasa', 'Lublub', 'Manlacbo', 'Masaroy', 'Mawab', 'Naili', 'Poblacion', 'Quinaspan', 'San Agustin', 'San Antonio', 'San Ramon', 'San Roque', 'Santo Niño', 'Tabod', 'Talisay', 'Tigmamale', 'Tigmalabong', 'Tublay', 'Tugas', 'Tuno', 'Yabnagan', 'Yayboboni']
}